a = int(input("Enter a number: "))
b = int(input("Enter another number: "))
print("ADDITION:", a + b)
print("SUBTRACTION:", a - b)
print("MULTIPLICATION:", a * b)
print("DIVISION:", a / b)
print("FLOOR DIVISION:", a // b)
print("MODULUS:", a % b)
print("EXPONENTIATION:", a ** b)
